# Stage 1: Building frontend
FROM node:24-alpine AS frontend
WORKDIR /app/www
RUN apk update --no-cache && apk add --no-cache tzdata git openssh
COPY www/package*.json .
RUN corepack enable && corepack prepare pnpm@latest-9 --activate && pnpm install

COPY www/api/ ./api
COPY www/components/ ./components
COPY www/config/ ./config
COPY www/hooks/ ./hooks
COPY www/i18n/ ./i18n
COPY www/lib/ ./lib
COPY www/pages/ ./pages
COPY www/public/ ./public
COPY www/store/ ./store
COPY www/styles/ ./styles
COPY www/types/ ./types

COPY www/*.js ./
COPY www/*.ts ./
COPY www/*.yaml ./
COPY www/*.json ./

RUN ls && mkdir -p ../cmd/frpp && pnpm build

# Stage 2: Building binary
FROM golang:1.25-alpine AS builder
WORKDIR /app
RUN apk update --no-cache && apk add --no-cache tzdata git bash
COPY go.mod go.sum ./
RUN CGO_ENABLED=0 GOPROXY=https://proxy.golang.org,direct go mod download
COPY . .
RUN rm -rf /app/cmd/frpp/out
COPY --from=frontend /app/www/out ./cmd/frpp/out
RUN rm -rf /app/dist/frp* && ./build.sh --skip-frontend --current 

# Stage 3: Build image
FROM alpine:latest
WORKDIR /app
RUN apk update --no-cache && apk add --no-cache tzdata git && mkdir -p /data
ENV TZ=UTC0
COPY --from=builder /app/frp-manager .

# web port
EXPOSE 9000
# rpc port
EXPOSE 9001

ENV DB_DSN=/data/data.db?_pragma=journal_mode(WAL)
ENTRYPOINT ["/app/frp-manager"]
CMD ["master"]
